### ISSUE TITLE
error flash built-in firmware

### ISSUE THREAD

**Issue by PriMEtor** [the-darkvoid/dfu-util-osx#1]
Hey, I'm using a bcm943602cs wifi+bt card with native support，but it seems like the firmware need upgrade to enable bluetooth in 10.12. 
I try the command the first time
```
./dfu-util 0x05AC 0x8290 /System/Library/Extensions/IOBluetoothFamily.kext/Contents/PlugIns/IOBluetoothUSBDFU.kext/Contents/Resources/20703_8290.dfu 
dfu-util, utility to flash dfu firmware into USB devices on OS X.
Based on original dfu-tool & dfu-programmer for Linux.

[i] Initiating DFU for USB device [05ac:8290].
The file /System/Library/Extensions/IOBluetoothFamily.kext/Contents/PlugIns/IOBluetoothUSBDFU.kext/Contents/Resources/20703_8290.dfu contains a DFU suffix with the following properties:
BCD device:	0x0119
Product ID:	0x8290
Vendor ID:	0x05AC
BCD DFU:	0x0100
Length:		16
CRC:		0x2B0D4668
[i] USB [05ac:8290 Љ v281] "Bluetooth USB Host Controller" by "Broadcom Corp."
[i] USB device has 1 configurations.
[i] DFU descriptor attributes 0x05 [Download, No Upload, Manifestation Tolerant, Reserved bits: 0x00], Timeout: 5000, Transfer Size: 64
[i] Device State appIDLE, Status No error condition is present
[i] Transitioning from STATE_APP_IDLE into STATE_DFU_IDLE.
[!] Device is not in dfu mode (state appDETACH).
[!] Failed to enter DFU mode.
```
and the next try
```
./dfu-util 0x05AC 0x8290/System/Library/Extensions/IOBluetoothFamily.kext/Contents/PlugIns/IOBluetoothUSBDFU.kext/Contents/Resources/20703_8290.dfu
dfu-util, utility to flash dfu firmware into USB devices on OS X.
Based on original dfu-tool & dfu-programmer for Linux.

[i] Initiating DFU for USB device [05ac:8290].
The file /System/Library/Extensions/IOBluetoothFamily.kext/Contents/PlugIns/IOBluetoothUSBDFU.kext/Contents/Resources/20703_8290.dfu contains a DFU suffix with the following properties:
BCD device:	0x0119
Product ID:	0x8290
Vendor ID:	0x05AC
BCD DFU:	0x0100
Length:		16
CRC:		0x2B0D4668
[i] USB [05ac:8290 Љ v281] "Bluetooth USB Host Controller" by "Broadcom Corp."
[i] USB device has 1 configurations.
[i] DFU descriptor attributes 0x05 [Download, No Upload, Manifestation Tolerant, Reserved bits: 0x00], Timeout: 5000, Transfer Size: 64
[i] Device State appDETACH, Status No error condition is present
[!] Device is not idle, unable to detach (state appDETACH).
[!] Failed to enter DFU mode.
```
I read the dfu_1.1.pdf, and i think the device did not change state of appDETACH to dfuIDLE after USB Reset.
I have no idea how to solve this, please help!

**Comment by robvanoostenrijk** [comment]
Are sure your card is not only supporting PatchRAM only? dfu-util would not
work for patchRAM devices.

**Comment by PriMEtor** [comment]
i did not use PatchRAM
[Adapter Card](http://www.ebay.com/itm/BCM94360CS2-BCM943224PCIEBT2-Card-To-NGFF-M-2-Key-A-E-Adapter-For-Mac-OS-/252520989216)
[WiFi-Bluetooth-Airport-Card](http://www.ebay.com/itm/Genuine-WiFi-Bluetooth-Airport-Card-BCM943602CS-for-Macbook-Pro-13-A1502-2015-/262351583043)
I use this two things in my hackintosh and the WiFi works fine, buf Bluetooth may need a firmware update by dfu, now I am finding  the way to do this.

**Comment by robvanoostenrijk** [comment]
What I meant is that the Bluetooth card you are using is most likely only
supporting PatchRAM. Full DFU upgrade is usually only available on
authentic Apple hardware.
A PatchRAM device cannot by DFU upgraded but requires BrcmPatchRAM to
handle the firmware.

**Comment by the-darkvoid** [comment]
What I mean is that the Bluetooth card you are using is most likely only
supporting PatchRAM. Full DFU upgrade is usually only available on
authentic Apple hardware.
A PatchRAM device cannot by DFU upgraded but requires BrcmPatchRAM to
handle the firmware.

**Comment by idevsoftware** [comment]
Sorry for resurrecting an old thread. I'm having the same issue with the same card, legitimate Apple hardware running a legit copy of macOS on an rMBP. I am trying to update the card firmware which seems to have gotten corrupted in one of the latest software updates (10.13.6), after which bluetooth no longer works. Any ideas on how to put the card in DFU mode? Thanks in advance.

**Comment by PriMEtor** [comment]
Hey, may be I can give you some information useful:
* The card firmware seems to be auto updated by the system at power up or some time, I once change a card from a 11.11 rMBP to a 11.12 machine，and the firmware version get updated
* I closed this issue because I find there is a hardware problem with the bcm943602cs,  some capacitor disappear in the circuit board. So I think this is why bluetooth not work

**Comment by idevsoftware** [comment]
Thank you for your feedback, the fact that the cards firmware gets uploaded on every boot seems reasonable to me. However I find it very suspicious that right after a software update it stopped working, the card now has a wrong product ID, bluetooth cannot be turned off on the preferences and no devices are detected.

**Comment by PriMEtor** [comment]
If possible, you can try a fresh install of 10.13.6 and see if problem still exists, be aware that this may erase your disk, it's recommended to backup your important data

**Comment by idevsoftware** [comment]
I did already. Tried reinstalling from scratch, going back all the way to El Capitan and even tried the Mojave beta. Bluetooth isn't even visible on versions < 10.13

**Comment by PriMEtor** [comment]
em... that looks really like a hardware problem

**Comment by idevsoftware** [comment]
right after a system software update? suspicious, to say the least
